# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-20 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='attn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attd.course')),
                ('useri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('is_prof', 'is_prof'),),
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=2017)),
                ('c1', models.IntegerField(default=0, null=True)),
                ('c2', models.IntegerField(default=0, null=True)),
                ('c3', models.IntegerField(default=0, null=True)),
                ('c4', models.IntegerField(default=0, null=True)),
                ('useri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('is_student', 'is_student'),),
            },
        ),
        migrations.AddField(
            model_name='attn',
            name='course',
            field=models.ForeignKey(on_delete=models.SET(0), to='attd.course'),
        ),
        migrations.AddField(
            model_name='attn',
            name='student',
            field=models.ForeignKey(on_delete=models.SET(0), to='attd.student'),
        ),
    ]
