# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-20 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='c1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='c2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='c3',
        ),
        migrations.RemoveField(
            model_name='student',
            name='c4',
        ),
        migrations.AddField(
            model_name='attn',
            name='ATT',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
